load data from data/cross_prompt_attributes/1/...
Loading embedding from cache...
Selected 40 samples.
Selected sample indices: [1691, 446, 689, 653, 945, 1548, 1244, 452, 1413, 916, 1447, 871, 1645, 476, 1368, 878, 746, 282, 1509, 1347, 151, 1577, 622, 1549, 1570, 915, 1348, 690, 794, 1359, 1299, 195, 908, 305, 1461, 410, 77, 939, 1183, 573]
================================
x_dev shape: (40, 1024)
y_dev shape: (40,)
================================
x_test shape: (1743, 1024)
y_test shape: (1743,)
================================
/home/takumi/anaconda3/envs/torch/lib/python3.10/site-packages/transformers/utils/generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_BERT.py", line 121, in <module>
    main(args)
  File "/mnt/c/Users/tandf/OneDrive - 電気通信大学/Src/DVRL/train_BERT.py", line 64, in main
    test_loader = DataLoader(x_test, y_test, batch_size=BATCH_SIZE)
TypeError: DataLoader.__init__() got multiple values for argument 'batch_size'